### ISSUE TITLE
Move schema loading to a separate class to decouple from CLI

### ISSUE THREAD

**Issue by jormaechea** [jormaechea/open-api-mocker#27]
## Requirements
- Move local schema loading logic to an specific class
- Call local schema loading from main class instead of from CLI layer 
- Allow to pass a `schema` option to the `OpenApiMocker` constructor to avoid calling `setSchema()` later.
- Move `watch` feature to the schema loaders

## Future improvements
- This has to allow the possibility of implementing more Schema loaders, such as `RemoteSchemaLoader`

## Retro-compatibility
- MUST keep the changes retro-compatible

**Comment by EdwardSalter** [comment]
Continuing from the conversation from #22 and specifically [this reply](https://github.com/jormaechea/open-api-mocker/issues/22#issuecomment-809824332), I spent some more time playing with that idea last night and found that my suggested code snippet wouldn't work since the schema needs to be loaded before `mock()` is called.

I ended up with an additional `OpenApiMocker.loadSchema(options)` function instead of `OpenApiMocker.setLoaderOptions`.
I will attach a draft PR too so you can take a look to see if that looks any better?

**Comment by jormaechea** [comment]
@EdwardSalter I just saw your comment. I've been working on some refactoring to achieve everything this Issue asks for.

Would you check the PR?
